# These are supported funding model platforms

github: [Barrot-Agent]
patreon: # Add your Patreon username here
open_collective: # Add your Open Collective username here
ko_fi: # Add your Ko-fi username here
tidelift: # Add your Tidelift platform-name/package-name here
community_bridge: # Add your Community Bridge project name here
liberapay: # Add your Liberapay username here
issuehunt: # Add your IssueHunt username here
otechie: # Add your Otechie username here
lfx_crowdfunding: # Add your LFX Crowdfunding project name here
custom: # Add up to 4 custom sponsorship URLs here
