name: Save Bundles to Repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate bundle
        run: echo "This is a test bundle" > Barrot-Bundles/test-$(date +%Y%m%d%H%M%S).txt

      - name: Commit bundle to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Barrot-Bundles/
          git commit -m "Add new bundle" || echo "No changes to commit"
          git push
