#!/usr/bin/env python3
"""
Node: Source Tracer
Auto-generated by Auto-Implementation Engine
Traces sources recursively to maximum depth
"""

from typing import Any, Dict, List
from datetime import datetime, timezone

class SourceTracer:
    """Trace sources recursively"""
    
    def __init__(self):
        self.traced_sources = []
    
    def trace_sources(self, data: Any, max_depth: int = 10) -> Dict[str, Any]:
        """Trace sources to maximum depth"""
        print(f"[TRACER] Tracing sources to depth {max_depth}")
        
        trace_tree = self._build_trace_tree(data, 0, max_depth)
        
        return {
            "root": data,
            "trace_tree": trace_tree,
            "max_depth_reached": self._get_max_depth(trace_tree),
            "total_sources": self._count_sources(trace_tree),
            "timestamp": datetime.now(timezone.utc).isoformat()
        }
    
    def _build_trace_tree(self, data: Any, depth: int, max_depth: int) -> Dict:
        """Build source trace tree"""
        if depth >= max_depth:
            return {"depth_limit": True, "depth": depth}
        
        tree = {
            "depth": depth,
            "data": str(data)[:100],
            "sources": []
        }
        
        # Extract sources
        sources = self._extract_sources(data)
        
        for source in sources:
            tree["sources"].append(self._build_trace_tree(source, depth + 1, max_depth))
        
        return tree
    
    def _extract_sources(self, data: Any) -> List[Any]:
        """Extract source references"""
        sources = []
        
        if isinstance(data, dict):
            for key in ["source", "sources", "origin", "from"]:
                if key in data:
                    value = data[key]
                    if isinstance(value, list):
                        sources.extend(value)
                    else:
                        sources.append(value)
        
        return sources
    
    def _get_max_depth(self, tree: Dict) -> int:
        """Get maximum depth reached"""
        if not tree.get("sources"):
            return tree.get("depth", 0)
        
        return max(self._get_max_depth(s) for s in tree["sources"])
    
    def _count_sources(self, tree: Dict) -> int:
        """Count total sources"""
        count = len(tree.get("sources", []))
        for source in tree.get("sources", []):
            count += self._count_sources(source)
        return count

def main():
    print("[TRACER] Source Tracer initialized")
    tracer = SourceTracer()

if __name__ == "__main__":
    main()
